from .site1_scraper import scrape_site1
from .site2_scraper import scrape_site2
from .site3_scraper import scrape_site3
from .site4_scraper import scrape_site4
from .site5_scraper import scrape_site5
from .site6_scraper import scrape_site6
from .site7_scraper import scrape_site7
from .site8_scraper import scrape_site8
from .site9_scraper import scrape_site9
