name: Package News Scrapping

on:
  schedule:
    - cron: '0 23 * * *'  # UTC 23:00 => 한국 시각 08:00

jobs:
  run-container:
    container:
      image: ghcr.io/${{ github.repository_owner }}/my-automation-image:latest
      options: --shm-size=2gb
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GHCR_TOKEN }}
    runs-on: ubuntu-latest
    env:
      EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
      EMAIL_RECIPIENT: ${{ vars.EMAIL_RECIPIENT }}
      CI: 'true'
      # 기사 수집 제한 환경 변수
      ARTICLE_LIMIT: ${{ vars.ARTICLE_LIMIT || '30' }}
      MIN_ARTICLE_SCORE: ${{ vars.MIN_ARTICLE_SCORE || '5.0' }}
      PER_KEYWORD_LIMIT: ${{ vars.PER_KEYWORD_LIMIT || '10' }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Run Automation Script
        run: |
          python main.py
