name: Package News Scrapping

on:
  workflow_dispatch:  # 수동 실행 트리거 추가
  schedule:
    - cron: '0 23 * * *'  # UTC 23:00 => 한국 시각 08:00

jobs:
  run-container:
    container:
      image: ghcr.io/${{ github.repository_owner }}/my-automation-image:latest
      options: --shm-size=2gb
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GHCR_TOKEN }}
    runs-on: ubuntu-latest
    env:
      EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
      EMAIL_RECIPIENT: ${{ vars.EMAIL_RECIPIENT }}
      EXCHANGE_EMAIL: ${{ vars.EXCHANGE_EMAIL }}
      EXCHANGE_PASSWORD: ${{ secrets.EXCHANGE_PASSWORD }}
      EXCHANGE_SERVER: ${{ vars.EXCHANGE_SERVER }}
      CI: 'true'
      # Google API 시크릿 추가
      GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
      GOOGLE_SEARCH_ENGINE_ID: ${{ secrets.GOOGLE_SEARCH_ENGINE_ID }}
      # 기사 수집 제한 환경 변수
      ARTICLE_LIMIT: ${{ vars.ARTICLE_LIMIT || '30' }}
      MIN_ARTICLE_SCORE: ${{ vars.MIN_ARTICLE_SCORE || '5.0' }}
      PER_KEYWORD_LIMIT: ${{ vars.PER_KEYWORD_LIMIT || '10' }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Run Automation Script
        run: |
          python main.py
