name: 뉴스 크롤링 자동화

on:
  schedule:
    # 매일 오전 9시에 실행 (UTC 기준, 한국 시간으로는 오후 6시)
    - cron: '0 9 * * *'
  # 수동으로 워크플로를 실행할 수 있는 옵션
  workflow_dispatch:

jobs:
  crawl:
    runs-on: ubuntu-latest
    
    env:
      CI: 'true'
      EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
      EMAIL_RECIPIENT: ${{ vars.EMAIL_RECIPIENT || 'dwcbj6214@gmail.com' }}
    
    steps:
    - name: 코드 체크아웃
      uses: actions/checkout@v4
      
    - name: Python 설정
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: 의존성 설치
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Chrome 설치
      run: |
        wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
        echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" | sudo tee /etc/apt/sources.list.d/google-chrome.list
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable
        
    - name: ChromeDriver 설치
      run: |
        CHROME_VERSION=$(google-chrome --version | awk '{print $3}' | cut -d. -f1)
        CHROMEDRIVER_VERSION=$(curl -s "https://chromedriver.storage.googleapis.com/LATEST_RELEASE_$CHROME_VERSION")
        wget "https://chromedriver.storage.googleapis.com/${CHROMEDRIVER_VERSION}/chromedriver_linux64.zip"
        unzip chromedriver_linux64.zip
        chmod +x chromedriver
        sudo mv chromedriver /usr/local/bin/
        
    - name: 크롤링 실행
      run: python main.py 